// darnafood-vue/src/components/CartDrawer.vue
<script setup>
import { useRouter } from 'vue-router'
import { useCartStore } from '../stores/cart'
import { useUIStore } from '../stores/ui'
import { dzd } from '../utils'

const router = useRouter()
const cart = useCartStore()
const ui = useUIStore()

function goCheckout() {
  ui.closeCart()
  router.push({ name: 'checkout' })
}
</script>

<template>
  <Teleport to="body">
    <div class="cart-overlay" :class="{ open: ui.cartOpen }" @click="ui.closeCart()"></div>
    <div class="cart-drawer" :class="{ open: ui.cartOpen }">
      <div class="drawer-head">
        <span class="drawer-head-title">🛒 Votre Panier</span>
        <button class="close-btn" @click="ui.closeCart()">✕</button>
      </div>
      <div class="drawer-body">
        <div v-if="cart.items.length === 0" class="empty-cart">
          <span class="ei">🍽️</span>
          <p>Votre panier est vide.<br>Ajoutez des plats pour commencer.</p>
        </div>
        <div v-else>
          <div v-for="item in cart.items" :key="item.id" class="d-item">
            <div class="d-item-icon" :style="{ background: item.gradient }">{{ item.emoji }}</div>
            <div class="d-item-info">
              <div class="d-item-name">{{ item.name }}</div>
              <div class="d-item-kitchen">{{ item.kitchenName }}</div>
              <div class="d-item-ctrl">
                <button class="qty-btn" @click="cart.remove(item.id)">−</button>
                <span class="qty-num">{{ item.qty }}</span>
                <button class="qty-btn" @click="cart.add(item, { id: item.kitchenId, name: item.kitchenName })">+</button>
              </div>
            </div>
            <div class="d-item-price">{{ dzd(item.price * item.qty) }}</div>
          </div>
        </div>
      </div>
      <div v-if="cart.items.length > 0" class="drawer-footer">
        <div class="total-row"><span>Total</span><span class="amt">{{ dzd(cart.total) }}</span></div>
        <div class="divider"></div>
        <button class="btn-primary btn-block" @click="goCheckout">✅ Commander</button>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.cart-overlay { position:fixed; inset:0; z-index:200; background:rgba(0,0,0,.65); backdrop-filter:blur(6px); opacity:0; pointer-events:none; transition:var(--ease-slow); }
.cart-overlay.open { opacity:1; pointer-events:all; }
.cart-drawer { position:fixed; top:0; right:0; bottom:0; z-index:201; width:410px; max-width:100vw; background:var(--bg-card); border-left:1px solid var(--border); display:flex; flex-direction:column; transform:translateX(100%); transition:var(--ease-slow); }
.cart-drawer.open { transform:translateX(0); }
.drawer-head { display:flex; align-items:center; justify-content:space-between; padding:22px 24px; border-bottom:1px solid var(--border); }
.drawer-head-title { font-size:19px; font-weight:700; }
.close-btn { width:34px; height:34px; border-radius:var(--r-sm); background:var(--bg-elevated); border:1px solid var(--border); color:var(--text-muted); font-size:16px; display:flex; align-items:center; justify-content:center; cursor:pointer; }
.close-btn:hover { color:var(--text); background:var(--border); }
.drawer-body { flex:1; overflow-y:auto; padding:22px 24px; }
.drawer-footer { padding:20px 24px; border-top:1px solid var(--border); }
.d-item { display:flex; gap:12px; align-items:center; padding:14px 0; border-bottom:1px solid var(--border); }
.d-item-icon { width:48px; height:48px; border-radius:var(--r-sm); display:flex; align-items:center; justify-content:center; font-size:22px; flex-shrink:0; }
.d-item-info { flex:1; }
.d-item-name { font-size:14px; font-weight:600; }
.d-item-kitchen { font-size:11px; color:var(--text-muted); margin-top:1px; }
.d-item-ctrl { display:flex; align-items:center; gap:8px; margin-top:7px; }
.qty-btn { width:24px; height:24px; border-radius:50%; background:var(--bg-elevated); border:1px solid var(--border); color:var(--text); font-size:15px; display:flex; align-items:center; justify-content:center; cursor:pointer; }
.qty-btn:hover { background:var(--primary-glow); border-color:var(--primary); }
.qty-num { font-size:13px; font-weight:700; min-width:18px; text-align:center; }
.d-item-price { font-size:14px; font-weight:700; color:var(--primary-light); }
.total-row { display:flex; justify-content:space-between; font-size:15px; font-weight:700; color:var(--text); }
.total-row .amt { color:var(--primary-light); }
.divider { height:1px; background:var(--border); margin:14px 0; }
.btn-block { width:100%; justify-content:center; padding:15px; font-size:15px; }
.empty-cart { text-align:center; padding:60px 0; color:var(--text-muted); }
.empty-cart .ei { font-size:60px; display:block; margin-bottom:14px; }
.empty-cart p { font-size:14px; line-height:1.6; }
</style>

// src/components/cart/CartDrawer.tsx
"use client";

import { useCartStore } from "@/store/cart";
import { X, Plus, Minus, ShoppingBag, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import Image from "next/image";

interface CartDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function CartDrawer({ isOpen, onClose }: CartDrawerProps) {
  const { items, updateQuantity, clearCart } = useCartStore();
  const router = useRouter();

  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);

  return (
    <>
      {/* Overlay */}
      <div
        onClick={onClose}
        style={{
          position: "fixed",
          inset: 0,
          background: "rgba(0,0,0,0.4)",
          zIndex: 200,
          backdropFilter: "blur(4px)",
          opacity: isOpen ? 1 : 0,
          pointerEvents: isOpen ? "auto" : "none",
          transition: "opacity 0.3s ease",
        }}
      />

      {/* Drawer */}
      <div
        style={{
          position: "fixed",
          top: 0,
          right: 0,
          height: "100%",
          width: "100%",
          maxWidth: 420,
          background: "var(--surface)",
          zIndex: 201,
          boxShadow: "var(--shadow-dropdown)",
          display: "flex",
          flexDirection: "column",
          transform: isOpen ? "translateX(0)" : "translateX(100%)",
          transition: "transform 0.3s cubic-bezier(0.4,0,0.2,1)",
        }}
      >
        {/* Header */}
        <div style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "1.25rem 1.5rem",
          borderBottom: "1px solid var(--border)",
          background: "var(--bg)",
          flexShrink: 0,
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
            <div style={{
              width: 36, height: 36, borderRadius: "var(--radius-md)",
              background: "var(--primary-light)",
              display: "flex", alignItems: "center", justifyContent: "center",
            }}>
              <ShoppingBag size={18} color="var(--primary)" />
            </div>
            <div>
              <h2 style={{ fontSize: "1rem", fontWeight: 700, color: "var(--text-primary)" }}>
                Votre Panier
              </h2>
              <p style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>
                {items.length} article{items.length !== 1 ? "s" : ""}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              width: 36, height: 36, borderRadius: "var(--radius-md)",
              border: "none", background: "var(--bg-secondary)",
              display: "flex", alignItems: "center", justifyContent: "center",
              cursor: "pointer", color: "var(--text-secondary)",
              transition: "all var(--transition-fast)",
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLElement).style.background = "var(--error-bg)";
              (e.currentTarget as HTMLElement).style.color = "var(--error)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLElement).style.background = "var(--bg-secondary)";
              (e.currentTarget as HTMLElement).style.color = "var(--text-secondary)";
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Items */}
        <div style={{ flex: 1, overflowY: "auto", padding: "1rem 1.5rem", display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          {items.length === 0 ? (
            <div style={{
              flex: 1, display: "flex", flexDirection: "column",
              alignItems: "center", justifyContent: "center", gap: "1rem",
              padding: "3rem 0",
            }}>
              <div style={{
                width: 72, height: 72, borderRadius: "50%",
                background: "var(--bg-secondary)",
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>
                <ShoppingBag size={30} color="var(--text-muted)" />
              </div>
              <div style={{ textAlign: "center" }}>
                <p style={{ fontWeight: 600, color: "var(--text-primary)", marginBottom: "0.25rem" }}>
                  Votre panier est vide
                </p>
                <p style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>
                  Ajoutez des plats pour commencer
                </p>
              </div>
            </div>
          ) : (
            items.map((item) => (
              <div
                key={item.dishId}
                style={{
                  display: "flex",
                  gap: "0.875rem",
                  padding: "0.875rem",
                  background: "var(--bg)",
                  borderRadius: "var(--radius-lg)",
                  border: "1px solid var(--border)",
                  alignItems: "center",
                }}
              >
                {/* Image */}
                <div style={{
                  width: 60, height: 60, borderRadius: "var(--radius-md)",
                  overflow: "hidden", background: "var(--bg-secondary)",
                  flexShrink: 0, position: "relative",
                }}>
                  {item.image ? (
                    <Image src={item.image} alt={item.name} fill style={{ objectFit: "cover" }} />
                  ) : (
                    <div style={{ width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.5rem" }}>
                      🍽️
                    </div>
                  )}
                </div>

                {/* Info */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{
                    fontWeight: 600, fontSize: "0.875rem", color: "var(--text-primary)",
                    overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
                  }}>
                    {item.name}
                  </p>
                  <p style={{ fontSize: "0.875rem", fontWeight: 700, color: "var(--primary)", marginTop: "2px" }}>
                    {(item.price * item.quantity).toLocaleString("fr-DZ")} DA
                  </p>
                </div>

                {/* Quantity */}
                <div style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.375rem",
                  background: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "var(--radius-md)",
                  padding: "4px",
                }}>
                  <button
                    onClick={() => updateQuantity(item.dishId, item.quantity - 1)}
                    style={{
                      width: 28, height: 28, borderRadius: "var(--radius-sm)",
                      border: "none", background: "var(--bg-secondary)",
                      display: "flex", alignItems: "center", justifyContent: "center",
                      cursor: "pointer", transition: "all var(--transition-fast)",
                    }}
                    onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--border)")}
                    onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--bg-secondary)")}
                  >
                    <Minus size={12} />
                  </button>
                  <span style={{ width: 24, textAlign: "center", fontSize: "0.875rem", fontWeight: 700, color: "var(--text-primary)" }}>
                    {item.quantity}
                  </span>
                  <button
                    onClick={() => updateQuantity(item.dishId, item.quantity + 1)}
                    style={{
                      width: 28, height: 28, borderRadius: "var(--radius-sm)",
                      border: "none", background: "var(--primary)",
                      display: "flex", alignItems: "center", justifyContent: "center",
                      cursor: "pointer", transition: "all var(--transition-fast)",
                    }}
                    onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--primary-dark)")}
                    onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.background = "var(--primary)")}
                  >
                    <Plus size={12} color="white" />
                  </button>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        {items.length > 0 && (
          <div style={{
            padding: "1.25rem 1.5rem",
            borderTop: "1px solid var(--border)",
            background: "var(--bg)",
            display: "flex",
            flexDirection: "column",
            gap: "1rem",
            flexShrink: 0,
          }}>
            {/* Total */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontWeight: 600, color: "var(--text-secondary)", fontSize: "0.9375rem" }}>Total</span>
              <span style={{ fontWeight: 800, fontSize: "1.25rem", color: "var(--primary)" }}>
                {total.toLocaleString("fr-DZ")} DA
              </span>
            </div>

            {/* Buttons */}
            <button
              onClick={() => { onClose(); router.push("/checkout"); }}
              className="btn btn-primary btn-lg"
              style={{ width: "100%", justifyContent: "center" }}
            >
              Commander — {total.toLocaleString("fr-DZ")} DA
            </button>

            <button
              onClick={clearCart}
              style={{
                display: "flex", alignItems: "center", justifyContent: "center",
                gap: "0.375rem", width: "100%",
                background: "none", border: "none",
                fontSize: "0.8125rem", color: "var(--text-muted)",
                cursor: "pointer", padding: "0.25rem",
                transition: "color var(--transition-fast)",
              }}
              onMouseEnter={(e) => ((e.currentTarget as HTMLElement).style.color = "var(--error)")}
              onMouseLeave={(e) => ((e.currentTarget as HTMLElement).style.color = "var(--text-muted)")}
            >
              <Trash2 size={13} /> Vider le panier
            </button>
          </div>
        )}
      </div>
    </>
  );
}
